### ISSUE TITLE
[H1] Create ERA5 surface forcing for ACCESS-OM2-01

### ISSUE THREAD

**Issue by willaguiar** [willaguiar/DSW-collaborative-project#1]
[Read H1 for more information](https://github.com/willaguiar/DSW-collaborative-project#h1---wind-forcing)

**Comment by adele157** [comment]
This is a big task! See discussion [here](https://github.com/COSIMA/access-om2/issues/242) and [here](https://forum.access-hive.org.au/t/cosima-meeting-minutes-2023/407/3) on COSIMA efforts already underway on this. NCAR is also working on an ERA-5do product.
