### ISSUE TITLE
[H2] What initial conditions to use

### ISSUE THREAD

**Issue by adele157** [willaguiar/DSW-collaborative-project#11]
Have we decided if we are starting these experiments from World Ocean Atlas obs or from an existing restart? I think from WOA would be cleaner as long as the spinup of DSW formation is fast. We'd need to plot time series of surface water mass transformation or DSW transport across the 1000m isobath to check. 

An advantage of choosing a later period is that we wouldn't have to rerun the control if we choose a time period that aligns with when high-frequency output for calculating DSW transports across the 1000m isobath are already available.

In either case, we will need to regrid either the restart or WOA onto the new vertical grid.

**Comment by willaguiar** [comment]
@adele157 for the easterlies project, what were the initial conditions? I wanna know if I need to change them before rerunning the RYF

**Comment by adele157** [comment]
They should be World Ocean Atlas and the model should be set to pick up the
file automatically. I would just give it a try.

**Comment by willaguiar** [comment]
@aekiss Next step I will create the initial conditions for the new run with reduced vertical resolution. Do you have a script you used to create the IC for the OM2-01 that I can use?
