### ISSUE TITLE
2-year repeat runs of ryf and ryf_5mdz without salt restoring

### ISSUE THREAD

**Issue by willaguiar** [willaguiar/DSW-collaborative-project#21]
We have decided in the last meeting to rerun the first 2 year of the ryf and ryf_5mdz simulations without salt restoring to check if this is controlling the changes seen in DSW formation between these simulations (how clean it is to compare the simulations, if we just changed the piston velocity). We can discuss the effect of salinity restoring here

**Comment by willaguiar** [comment]
I have been getting a _salinity out of bounds_ error right in the beginning of the run, around the equator at surface.

`FATAL from PE  2218:  Error: salinity out of range with value    -6.606223738664E-03 at (i,j,k) = (2316,1236,  1),  (lon,lat,dpt) = (  -48.4500,   -0.9500,    0.5453 m)`
Which makes me think that the ATM forcing without the salinity restoring might be causing a strong salinity decrease there. Any other suggestion?

The only things I changed in the simulations were the parameters for the salt restore
```
salt_restore_as_salt_flux = .false.,                (was true before)
use_waterflux = .false.,                            (was true before)
max_delta_salinity_restore = 0,                     (was 0.5 before)
salt_restore_under_ice = .false.,                   (was true before)
salt_restore_tscale = 0                             (was 10 before)
```

**Comment by fabiobdias** [comment]
If I remember correctly you should just set “salt_restore_tscale” as a negative value (e.g. -1) to deactivate the salinity restoring. Any reason to change other parameters on the namelist?

From: Wilton Aguiar ***@***.***>
Date: Wednesday, 14 June 2023 at 2:26 pm
To: willaguiar/DSW-collaborative-project ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [willaguiar/DSW-collaborative-project] 2-year repeat runs of ryf and ryf_5mdz without salt restoring (Issue #21)

I have been getting a salinity out of bounds error right in the beginning of the run, around the equator at surface.

FATAL from PE 2218: Error: salinity out of range with value -6.606223738664E-03 at (i,j,k) = (2316,1236, 1), (lon,lat,dpt) = ( -48.4500, -0.9500, 0.5453 m)
Which makes me think that the ATM forcing without the salinity restoring might be causing a strong salinity decrease there. Any other suggestion?

The only things I changed in the simulations were the parameters for the salt restore

salt_restore_as_salt_flux = .false.,                (was true before)

use_waterflux = .false.,                            (was true before)

max_delta_salinity_restore = 0,                     (was 0.5 before)

salt_restore_under_ice = .false.,                   (was true before)

salt_restore_tscale = 0                             (was 10 before)

**Comment by willaguiar** [comment]
Not really.  Just wasn't sure how mom deals with the other parameters after changing `salt_restore_as_salt_flux, `and `use_waterflux`. (eg., if having `max_delta_salinity_restore` different than 0 overwrites the` salt_restore_as_salt_flux`). So I changed everything to push towards no salt restoring.

**Comment by adele157** [comment]
Yep, you definitely want to keep `use_waterflux = .true.`. This is not just for the restoring, but for all the atmosphere / sea ice freshwater fluxes. Otherwise it uses virtual salt fluxes.
