### ISSUE TITLE
[H1] DSW formation in ACCESS-ERA5 vs ACCESS-JRA

### ISSUE THREAD

**Issue by willaguiar** [willaguiar/DSW-collaborative-project#3]
The outputs from ACCESS-ERA5 can be compared with 01deg_jra55v13_ryf9091

[Read H1 for more information](https://github.com/willaguiar/DSW-collaborative-project#h1---wind-forcing)

**Comment by adele157** [comment]
Do we mean here in Ryan's ERA5 runs? Were those done at 0.1deg?

I'll also note here that we used to get DSW formation fine in our old MOM5-SIS runs forced by CORE (e.g. Morrison et al. 2020). Given that, maybe it's worth adding CORE winds to our [comparison of CM2/JRA winds](https://github.com/willaguiar/DSW-collaborative-project/issues/10), so we have 2 references for strength / structure of winds that we know work?

**Comment by willaguiar** [comment]
I actually was first thinking of running OM2-01 with ERA5 forcing - but then realized Ryan is already working on that. I will close this issue for now, so we can focus on JRA/CORE/CM2 winds comparison.
