### ISSUE TITLE
[H2] Alter ACCESS-OM2-01 minimum ocean cell depth to 21m, 4 vertical levels

### ISSUE THREAD

**Issue by willaguiar** [willaguiar/DSW-collaborative-project#4]
Alter the minimum ocean depth cell in ACCESS-OM2-01 from 10m to 25m depth. 

[Read H2 for more information](https://github.com/willaguiar/DSW-collaborative-project#h2----fine-grid-ocean-resolution)

**Comment by willaguiar** [comment]
Notice I changed the minimum bathymetry depth to 25 m, instead of 40m. This value can still contemplate 4 vertical levels ( as in OM2-025) in the new KDZ75_5mdz grid. For reference check [here ](https://github.com/willaguiar/DSW-collaborative-project/issues/9#issuecomment-1491259586) and [here](https://github.com/willaguiar/DSW-collaborative-project/blob/a30cc7fb4198f610e0b9d60090276a21699de872/Zgrid_levels)

**Comment by willaguiar** [comment]
Details below on the changes in bathymetry (new bathymetry - old). A 4-level cutoff for the bathymetry was used, so depths below 21m were turned into land. Almost no change happens around Antarctica (except in the Antarctica peninsula). Most of the changes seem to happen in the Arctic.
![Dbath_Antarctica](https://user-images.githubusercontent.com/70033934/229641610-0fff0337-28a6-4ce2-ad49-74e13ebefe94.png)
![Dbath_global](https://user-images.githubusercontent.com/70033934/229641614-bc8d80e5-70fe-40e3-9e7c-a4de1d04a142.png)

**Comment by dkhutch** [comment]
That is reassuring to see that Antarctic bathymetry is hardly affected!

**Comment by willaguiar** [comment]
I started running the model with the new topography, created as above. Model crashes with the new topography with the following error
`Error from ocean_thickness_mod: Free surface penetrating rock! Model unstable.`
Unexpected, since the only think change in the topography was a deepening of the shallow seas. Anyways, I found out this issue happened before in a [previous fix done in the topography ](https://github.com/COSIMA/access-om2/issues/99#issuecomment-401532257). I will try fix the issue with the tool described in the link ( and perhaps update the lance/ocean masks too). PS: this information might be useful for panan005 and panan0025 too.

**Comment by adele157** [comment]
That seems odd. You have the same land / sea mask right? If you just
deepened the ocean there shouldn’t be any new non-advective cells. Are you
using the same time step as the original RYF used for the spin up?

Can you see what grid cell the crash is happening in?

**Comment by dkhutch** [comment]
I just realised you are now going for 5-level minimum (29 m) instead of 4-level. That sounds fine to have a bit more margin for stability, but just wondering, did you have problems with the 4-level version?

**Comment by willaguiar** [comment]
> That seems odd. You have the same land / sea mask right? If you just deepened the ocean there shouldn’t be any new non-advective cells. Are you using the same time step as the original RYF used for the spin up? Can you see what grid cell the crash is happening in?
> […](#)

Yes. I used the same land/sea mask (from here:` /g/data/ik11/inputs/access-om2/input_08022019/mom_01deg`). Timestep is 300 ( it was working before using the original topography in the dir above). access-om2.err do not say which grid cells the error come from tho. The only thing that comes to my mind is that perhaps I edited the wrong bathymetry file ( before the changes done by @aekiss).
I used `/g/data/ik11/inputs/access-om2/input_08022019/mom_01deg/topog.nc` which was pointed in the config.yaml.

rundir is in `/home/156/wf4500/access-om2-01/ryf`

**Comment by willaguiar** [comment]
> I just realised you are now going for 5-level minimum (29 m) instead of 4-level. That sounds fine to have a bit more margin for stability, but just wondering, did you have problems with the 4-level version?

Not really. I wanted to deepen anything with Z<25m, and the depths of the new grid close to 25m were 21m (4 levels) and 29m (5 levels). So I just chose 29 m arbitrarily. I can probably set to 21m, but maybe the free surface problem would be worse?

**Comment by willaguiar** [comment]
I think I found the problem. The flag for land (-1e30f) was not saved in the final netcdf. changing that and running again

**Comment by willaguiar** [comment]
> I found the problem. The flag for land (-1e30f) was not saved in the final netcdf. changing that and running again

Problem fixed by changing the land flag. RYF simulation is running now (day 5) with the new topography [zmax=21m, 4 levels]
