### ISSUE TITLE
[H2] Change coarse vertical grid for OM2-01

### ISSUE THREAD

**Issue by willaguiar** [willaguiar/DSW-collaborative-project#9]
[Read H2 for more information](https://github.com/willaguiar/DSW-collaborative-project#h2----fine-grid-ocean-resolution)

**Comment by willaguiar** [comment]
OM2-025 has 50 levels starting from ~1m, and OM2-01 has 75 starting from ~0.5m. 
The plot below shows the average thickness of the z cells (dzt) for each resolution. dzt increases by up to 10m from 0.25^o to 0.01^o, in the upper 300m of the water column 

Should we change the vertical resolution of OM2-01 to just be similar to OM2-025? Or

**Comment by adele157** [comment]
Perhaps a factor to consider here is how long are we going to need to run the model to see if DSW formation shuts off. I'm thinking 10 years? Which means we can probably ideally afford 1 or 2 vertical resolution tests? 

Figure 7 from Stewart et al. 2017 is handy to compare vertical resolution from a few different models (note the KDS ones are all Kial's different test versions - we use KDS75). We used to use GFDL50 which has terrible upper ocean resolution compared to all the other models there. We _think_ that we started get DSW formation when we changed from GFDL50 to KDS75 (but other things changed at the same time).

<img width="1038" alt="Screen Shot 2023-03-06 at 10 37 58 am" src="https://user-images.githubusercontent.com/8506963/222992701-12370c3a-665b-4660-be26-1b27929e6fe3.png">

What about following Kial's method for setting the vertical resolution from that paper and do 1 test with the upper cell thickness = 10m (depending on how that goes we could follow up with another test after)?

**Comment by willaguiar** [comment]
Sure - that could be a good test. Do you think we should change only the upper cell(s) thickness in the first test, or change  also the thickness in the cells deeper than 1km? It seems that from GFDL50 to KDS75 the cells between 1km and 3 km thickened about 50m. And from OM01 to OM025 the cells at the same depth range thickens up to 40m. If this cell thickening increases mixing too much along the overflow path, maybe DSW might not be fully exported to the abyss, even if it is formed along the shelf.

**Comment by adele157** [comment]
Andy, Wilma and I chatted about this yesterday, and thought perhaps it would be best to change the upper 500m, but not the resolution below that. i.e. something like this (black is current, red is new):

<img width="400" alt="Screen Shot 2023-03-06 at 10 37 58 am" src="https://user-images.githubusercontent.com/8506963/223594196-846a407f-c5be-472b-8925-faf0c602ca00.jpg">

That way we can isolate the resolution impact on the upper ocean mixing, but not change the overflow mixing.

**Comment by PaulSpence** [comment]
Maybe check to verify that there is no DSW in GFDL50. Then take that models vertical grid (or take the exising ACCESS-om2-025 grid, rather than make up another one) and use it to toy with. 

The goal is to shut down DSW by changing the vertical grid, right? If changing the upper 500m doesn't work, then whats the next step? Maybe start by running ACCESS-om2-01 with the 50 layer ACCESS-om2-025 grid and shut it off and then work from there?

**Comment by adele157** [comment]
ACCESS-om2-025 still has only a 2m thick upper cell. I think we might need a larger change to the vertical grid than that  (at least a 5m thick upper cell)?

**Comment by willaguiar** [comment]
I was looking at the v_grid for OM2-01  and for KDS75. They are different at z>2000m (fig below). If I use Kial's method to create the new KDS grid (KDS75_5mdz) with minimum dz=5m, the grid below 2000m wouldn't match OM01-grid. 

Since OM01 grid matches well with the KDS75 above 2000m, I will do the following:
1-Use Kial's method to produce a new grid similar to KDS75 (new grid: KDS75_500mcrossing_5mdz), but changing the minimum layer thickness of 5 m, **and** weakening the slope of the hyperbolic function . This new grid crosses the OM2-01 vertical grid in z~500m (bottom plot);
2-Substitute the upper 500m of OM2-01 by the upper 500m of KDS75_500mcrossing_5mdz.
3-check for discontinuities ( or grid inconsistencies) in around 500m

But before I do that...@adele157 could this difference between KDS75 and OM01 be due to the variation of the thickness in z*?


In the figure: 
OM2-01=grid from ocean_vgrid.nc file of OM2-01
KDS75=KDS75 grid from Stewart et al 2017
KDS75_5mdz= Grid with same parameters as KDS75, except with minimum dz=5m
KDS75_500mcrossing_5mdz= Grid with same parameters as KDS75, except with minimum dz=5m **and** with a softened slope.

![Image](https://user-images.githubusercontent.com/70033934/225817117-8d1626d1-5136-4e27-bed2-7e21643eb76a.png)

**Comment by adele157** [comment]
Sounds like a good approach @willaguiar. Any idea why the OM2-01 grid looks so wacky below 3000m? Is it a 2D field that includes the partial cell depths at the ocean bottom perhaps? What's the full path of the `ocean_vgrid.nc` file you're using?

**Comment by willaguiar** [comment]
@adele157 correction -  I used ocean.nc (st_ocean var) for the last netcdf of the 01deg_jra55v13_ryf9091 for OM2-01 in the [previous plot](https://github.com/willaguiar/DSW-collaborative-project/issues/9#issuecomment-1473136488). I just realized st_ocean would have the effect of changing dz. I replotted the graph above now using this file for OM2-01 ocean_vgrid:

OM2-01 =/g/data/hh5/tmp/cosima/bathymetry/ocean_vgrid.nc (Let me know If this is the appropriate file)
KDS75=KDS75 grid from Stewart et al 2017 (got it from Kial)
KDS75_5mdz= Grid with same parameters as KDS75, except with minimum dz=5m


It seems to me that the input grid for OM2-01 is actually KDS75. So KDS75_5mdz (60 vertical levels) seem to be close enough to be used for the experiments- What do you think?


![KDS_zgrids2-3](https://user-images.githubusercontent.com/70033934/226219761-69e07a6b-ee28-4505-9abe-caff973542da.png)
![KDS_zgrids2-2](https://user-images.githubusercontent.com/70033934/226219776-4c973be5-d971-4a46-8c2a-989332cfca92.png)

**Comment by adele157** [comment]
Yes, I'm happy just to go with the KDS75_5mdz rather than merging the two
grids.

**Comment by willaguiar** [comment]
Info:
In KDS75_5mdz the first[ 4 levels go up to ~21m](https://github.com/willaguiar/DSW-collaborative-project/blob/a30cc7fb4198f610e0b9d60090276a21699de872/Zgrid_levels) (as @dkhutch estimated. :D). So we can probably get away with a minimum topography depth of 25m. 

Since we decided on the grid I will close this issue and the bathymetry description to [here](https://github.com/willaguiar/DSW-collaborative-project/issues/4#issue-1600372551)
